# Example 2: Minimal configuration for 2 tests.
# Run 2 tests on any available *single* device in the device pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp-1023370588.ipa
  testApp: apps/MyDemoAppUITests-Runner-1966216460.ipa

suites:
  - name: "Example 2 - testProductListingPageAddItemToCart and testProductDetailsPrice"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddItemToCart","MyDemoAppUITests.ProductDetailsTest/testProductDetailsPrice"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
