# Example 5: Parallel execution using dynamic devices
# Run two tests on separate random iPhone devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp.ipa
  testApp: apps/MyDemoAppUITests-Runner.ipa

suites:
  - name: "Example 5 - testProductListingPageAddMultipleItemsToCart"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddMultipleItemsToCart"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
        platformVersion: "14"
  - name: "Example 5 - testProductDetailsColorsSwitch"
    testOptions:
      class: ["MyDemoAppUITests.ProductDetailsTest/testProductDetailsColorsSwitch"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
        platformVersion: "14"

reporters:
  junit:
    enabled: true
    filename: ./reports/example-5-report.xml

artifacts:
  download:
    when: always
    match:
    - "*"
    directory: ./reports/
