# Example 4: Run in parallel on hard-coded devices
# Run two tests on separate specific devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10
  metadata:
    tags:
      - ios
      - xcuitest
      - ex4
  build: Sauce XCUITest Real Devices

xcuitest:
  app: ./apps/SauceLabs.Mobile.Sample.XCUITest.App.ipa
  testApp: ./apps/SwagLabsMobileAppUITests-Runner.app

suites:
  - name: "Sauce Labs XCUITest Tests from Example 4 - testNoPasswordLogin"
    testOptions:
      class: ["SwagLabsMobileAppUITests.LoginTests/testNoPasswordLogin"]
    devices:
      # Run on a fixed device
      - name: iPhone_XS_13_real
  - name: "Sauce Labs XCUITest Tests from Example 4 - testNoMatchLogin"
    testOptions:
      class: ["SwagLabsMobileAppUITests.LoginTests/testNoMatchLogin"]
    devices:
      # Run on a fixed device
      - name: iPhone_11_14_real

reporters:
  junit:
    enabled: true
    filename: ./reports/example-4-report.xml

artifacts:
  download:
    when: always
    match:
    - "*"
    directory: ./reports/
