# Example 5: Parallel execution using dynamic devices
# Run two tests on separate random iPhone devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp-1023370588.ipa
  testApp: apps/MyDemoAppUITests-Runner-1966216460.ipa

suites:
  - name: "Example 5 - testProductListingPageAddMultipleItemsToCart"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddMultipleItemsToCart"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
  - name: "Example 5 - testProductDetailsColorsSwitch"
    testOptions:
      class: ["MyDemoAppUITests.ProductDetailsTest/testProductDetailsColorsSwitch"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
