# Example 1: minimal configuration.
# Run all tests on any available *single* device in the device pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp.ipa
  testApp: apps/MyDemoAppUITests-Runner.ipa

suites:
  - name: "Example 1 - Run all tests"
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
        platformVersion: "14"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
