# Example 4: Run in parallel on hard-coded devices
# Run two tests on separate specific devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp-1023370588.ipa
  testApp: apps/MyDemoAppUITests-Runner-1966216460.ipa

suites:
  - name: "Example 4 - testProductListingPageAddMultipleItemsToCart"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddMultipleItemsToCart"]
    devices:
      # Run on a fixed device
      - name: iPhone_12_14_real
  - name: "Example 4 - testProductDetailsColorsSwitch"
    testOptions:
      class: ["MyDemoAppUITests.ProductDetailsTest/testProductDetailsColorsSwitch"]
    devices:
      # Run on a fixed device
      - name: iPhone_11_14_real

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
