# Example 4: Run in parallel on hard-coded devices
# Run two tests on separate specific devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp.ipa
  testApp: apps/MyDemoAppUITests-Runner.ipa

suites:
  - name: "Example 4 - testProductListingPageAddMultipleItemsToCart"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddMultipleItemsToCart"]
    devices:
      # Run on a fixed device
      - name: iPhone_12_14_real
        platformVersion: "14"
  - name: "Example 4 - testProductDetailsColorsSwitch"
    testOptions:
      class: ["MyDemoAppUITests.ProductDetailsTest/testProductDetailsColorsSwitch"]
    devices:
      # Run on a fixed device
      - name: iPhone_11_14_real
        platformVersion: "14"

reporters:
  junit:
    enabled: true
    filename: ./reports/example-4-report.xml

artifacts:
  download:
    when: always
    match:
    - "*"
    directory: ./reports/
