# Example 3: Run each test on its own device
# Run two tests on separately available devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10
  metadata:
    tags:
      - ios
      - xcuitest
      - ex3
  build: Sauce XCUITest Real Devices

xcuitest:
  app: ./apps/SauceLabs.Mobile.Sample.XCUITest.App.ipa
  testApp: ./apps/SwagLabsMobileAppUITests-Runner.app

suites:
  - name: "Sauce Labs XCUITest Tests from Example 3 - testSuccessfulLogin"
    testOptions:
      class: ["SwagLabsMobileAppUITests.LoginTests/testSuccessfulLogin"]
    devices:
      # Run on a random iPhone 11 device
      - name: "iPhone 11.*"
  - name: "Sauce Labs XCUITest Tests from Example 3 - testCompleteFlow"
    testOptions:
      class: ["SwagLabsMobileAppUITests.SwagLabsFlow/testCompleteFlow"]
    devices:
      # Run on a random iPhone X device
      - name: "iPhone X.*"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
