# Example 3: Run each test on its own device
# Run two tests on separately available devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10

xcuitest:
  app: apps/MyDemoApp.ipa
  testApp: apps/MyDemoAppUITests-Runner.ipa

suites:
  - name: "Example 3 - testProductListingPageAddMultipleItemsToCart"
    testOptions:
      class: ["MyDemoAppUITests.ProductListingPageTest/testProductListingPageAddMultipleItemsToCart"]
    devices:
      # Run on a random iPhone 11 device
      - name: "iPhone 11.*"
        platformVersion: "14"
  - name: "Example 3 - testProductDetailsColorsSwitch"
    testOptions:
      class: ["MyDemoAppUITests.ProductDetailsTest/testProductDetailsColorsSwitch"]
    devices:
      # Run on a random iPhone X device
      - name: "iPhone X.*"
        platformVersion: "14"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
